### ISSUE TITLE
Composite onClose callback

### ISSUE THREAD

**Issue by cheymonty** [Azure-Samples/communication-services-ui-library-react-native#20]
### This issue is for a: 
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> When creating the composite, there should be a callback parameter that is called when the composite is closed (due to the meeting ending for all or the user leaving themselves)

**Comment by JoshuaLai** [comment]
Thanks for the feedback @cheymonty. Since these sample are built off of the native UI composites. We would need the feature to exist on those underlying libraries first. I recommend creating a git issue against those repos or provide feedback here: https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858 and we can try to get the feature added to our backlog!

iOS: https://github.com/Azure/communication-ui-library-ios
Android: https://github.com/Azure/communication-ui-library-android
cc @iaulakh
